apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deploy
  labels:
    app: gitops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: vardhan027/git-project-demo:v1
          ports:
            - containerPort: 80
          imagePullPolicy: Always
